---
- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
